version: '3'

services:
  my_money_frontend:
    container_name: my_money_frontend
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    command: npm run dev
  